platform:
  sepolicy_dirs:
    - device/google/redbull-sepolicy

includes:
  - pixel.yml

filters:
  dep_files:
    match:
      # Required by libOmxSwVencMpeg4
      - vendor/lib/libMpeg4SwEncoder.so
      - vendor/lib64/libMpeg4SwEncoder.so

      # Required by vendor.qti.hardware.display.composer-service
      - vendor/lib64/libthermalclient.so

      # Required by chre
      - vendor/lib/libadsprpc.so
      - vendor/lib64/libadsprpc.so

      # Required by libOmxVenc
      - vendor/lib/libfastcvopt.so
      - vendor/lib64/libfastcvopt.so

      # Needed to pass checkvintf
      - vendor/etc/vintf/manifest/android.hardware.graphics.mapper-impl-qti-display.xml
      - vendor/etc/vintf/manifest/c2_manifest_vendor.xml
      - vendor/etc/vintf/manifest/pixel-display-default.xml
      - vendor/etc/vintf/manifest/vendor.qti.hardware.display.allocator-service.xml
      - vendor/etc/vintf/manifest/vendor.qti.hardware.display.composer-service.xml

  overlay_files:
    match:
      # Workaround for aapt2 output parsing bug
      - HbmSVManager__auto_generated_rro_vendor.apk
