filters:
  props:
    match:
      # GMS
      - ro.opa.eligible_device
      - ro.atrace.core.services
      - ro.com.google.clientidbase
      - ro.error.receiver.system.apps

    prefix:
      # Gboard
      - ro.com.google.ime.
      - ro.storage_manager.

  files:
    match:
      - product/app/arcore/arcore.apk
      - product/app/CalculatorGooglePrebuilt/CalculatorGooglePrebuilt.apk
      - product/app/CalendarGooglePrebuilt/CalendarGooglePrebuilt.apk
      - product/app/Chrome-Stub/Chrome-Stub.apk
      - product/app/Chrome/Chrome.apk.gz
      - product/app/Drive/Drive.apk
      - product/app/GoogleContacts/GoogleContacts.apk
      - product/app/GoogleContactsSyncAdapter/GoogleContactsSyncAdapter.apk
      - product/app/GoogleTTS/GoogleTTS.apk
      - product/app/LatinIMEGooglePrebuilt/LatinIMEGooglePrebuilt.apk
      - product/app/LocationHistoryPrebuilt/LocationHistoryPrebuilt.apk
      - product/app/Maps/Maps.apk
      - product/app/ModuleMetadataGoogle/ModuleMetadataGoogle.apk
      - product/app/Photos/Photos.apk
      - product/app/PlayAutoInstallConfig/PlayAutoInstallConfig.apk
      - product/app/PrebuiltDeskClockGoogle/PrebuiltDeskClockGoogle.apk
      - product/app/PrebuiltGmail/PrebuiltGmail.apk
      - product/app/talkback/talkback.apk
      - product/app/TrichromeLibrary-Stub/TrichromeLibrary-Stub.apk
      - product/app/TrichromeLibrary/TrichromeLibrary.apk.gz
      - product/app/Tycho/Tycho.apk
      - product/app/Videos/Videos.apk
      - product/app/WebViewGoogle-Stub/WebViewGoogle-Stub.apk
      - product/app/WebViewGoogle/WebViewGoogle.apk.gz
      - product/app/YouTube/YouTube.apk
      - product/app/YouTubeMusicPrebuilt/YouTubeMusicPrebuilt.apk
      - product/etc/permissions/split-permissions-google.xml
      - product/etc/preferred-apps/google.xml
      - product/etc/sysconfig/google-staged-installer-whitelist.xml
      - product/framework/com.google.android.dialer.support.jar
      - product/priv-app/AndroidAutoStubPrebuilt/AndroidAutoStubPrebuilt.apk
      - product/priv-app/ConfigUpdater/ConfigUpdater.apk
      - product/priv-app/FilesPrebuilt/FilesPrebuilt.apk
      - product/priv-app/GCS/GCS.apk
      - product/priv-app/GoogleDialer/GoogleDialer.apk
      - product/priv-app/GoogleOneTimeInitializer/GoogleOneTimeInitializer.apk
      - product/priv-app/GoogleRestorePrebuilt/GoogleRestorePrebuilt.apk
      - product/priv-app/PartnerSetupPrebuilt/PartnerSetupPrebuilt.apk
      - product/priv-app/Phonesky/Phonesky.apk
      - product/priv-app/PrebuiltBugle/PrebuiltBugle.apk
      - product/priv-app/RecorderPrebuilt/RecorderPrebuilt.apk
      - product/priv-app/SetupWizardPrebuilt/SetupWizardPrebuilt.apk
      - product/priv-app/Velvet/Velvet.apk
      - product/priv-app/WellbeingPrebuilt/WellbeingPrebuilt.apk
      - system_ext/priv-app/GoogleServicesFramework/GoogleServicesFramework.apk
      - system/etc/permissions/privapp-permissions-google.xml

    prefix:
      - product/etc/sysconfig/preinstalled-packages-
      - product/priv-app/PrebuiltGmsCore/
      - product/usr/share/ime/google/
      - product/usr/srec/

  overlay_values:
    substring:
      - com.google.android.gms
